mysite/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('login/', auth_views.LoginView.as_view() , name='login'),
    path('logout/', auth_views.LogoutView.as_view() , name='logout'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('post-add/', views.post_add , name='post_add'),
    path('post-edit/<int:post_id>/', views.post_edit , name='post_edit'),
    path('post-delete/<int:post_id>/', views.post_delete , name='post_delete'),
    path('post_point_list/<int:post_id>/', views.post_point_list , name='post_point_list'),
    path('post_point_add/<int:post_id>/', views.post_point_add , name='post_point_add'),
    path('post_point_edit/<int:post_point_id>/', views.post_point_edit, name='post_point_edit'),
    path('post_point_delete/<int:post_point_id>/', views.post_point_delete, name='post_point_delete'),
    path('sign-up/',views.sign_up, name='sign-up'),
path('profile/', views.edit_profile, name='edit_profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', namespace='blog')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from slugify import slugify

class Post(models.Model):
    STATUS_CHOISES=(('draft','Draft'),('published','Published'),)

    title=models.CharField(max_length=250,verbose_name='Post name')
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts',verbose_name='Author')
    short_description=models.CharField(max_length=400,verbose_name='Description')
    publish=models.DateTimeField(default=timezone.now,verbose_name='Publish date')
    tags = TaggableManager()
    created = models.DateTimeField(auto_now_add=True, verbose_name='Create date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Update')
    status=models.CharField(max_length=10, choices=STATUS_CHOISES,default='draft')
    image=models.ImageField(upload_to='porodact_images/',verbose_name='Image',blank=False)

    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title
    def get_absolut_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        return super(Post,self).save(*args,**kwargs)

def save_images(instance,filename):
    post_id=instance.post.id
    return 'gallery_images/{}/{}'.format(post_id,filename)

class PostPoint(models.Model):
    post_header=models.CharField(max_length=250,default='HEADER')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,default=None)
    post_point_text=models.TextField(verbose_name='Post point')
    post_images = models.ImageField(upload_to=save_images, verbose_name='Image point', blank=True,)
    def __str__(self):
        return 'Post point {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def str(self):
        return 'Комментарий написан {} о {}'.format(self.name, self.post)

mysite/blog/forms.py
from .models import Comment, Post, PostPoint, User
from django import forms

class SearchForm(forms.Form):
    query=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control mr-sm-2',
        'type':'search',
        'placeholder':'Search',
        'aria-label':'Search'
    }))

class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name',
                'username','email')

class UserCreateForm(forms.ModelForm):
    password=forms.CharField(max_length=40,
                            widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password')

class PostPointForm(forms.ModelForm):
    class Meta:
        model=PostPoint
        fields=('post_header','post_point_text','post_images')

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','short_description','image','tags')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "id":"inputLogin",
        "class":"form-control",
        "placeholder":"login",
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "type": "password",
        "id":"inputPassword",
        "class":"form-control",
        "placeholder":"0000",
    }))

mysite/blog/views.py
from django.shortcuts import render ,get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from .models import Post, PostPoint, Comment, User
from django.views.generic import ListView
from .forms import CommentForm, LoginForm, PostForm, PostPointForm, UserCreateForm
from taggit.models import Tag
from django.db.models import Count
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from .forms import UserEditForm, SearchForm



@login_required
def edit_profile(request):
    user_form = UserEditForm(
        instance=request.user)
    if request.method == 'POST':
        user_form = UserEditForm(
            request.POST,
            instance=request.user)
        if user_form.is_valid():
            user_form.save()
    return render(request,
                  'blog/account/profile.html',
                  {'user_form': user_form})
def sign_up(request):
    user_form=UserCreateForm()
    if request.method == 'POST':
        user_form=UserCreateForm(request.POST)
        if user_form.is_valid():
            new_user=User.objects.create_user(**user_form.cleaned_data)
            new_user.save()
            login(request, authenticate(username=user_form.cleaned_data['username'],
                                        password=user_form.cleaned_data['password']))
            return redirect('blog:post_list')
    return render(request,'registration/sign_up.html',
                                {'user_form':user_form})

@login_required
def post_point_delete(request, post_point_id):
    try:
        post_point = get_object_or_404(PostPoint,
                                       id=post_point_id)
        post_point.delete()
        return redirect('blog:post_point_list', post_id=post_point.post.id)
    except PostPoint.DoesNotExist:
        return redirect('blog:post_list')

@login_required
def post_point_edit(request, post_point_id):
    post_point = get_object_or_404(PostPoint, id=post_point_id)
    post = get_object_or_404(Post, id=post_point.post.id)
    post_point_edit_form = PostPointForm(instance=post_point)
    if request.method == 'POST':
        post_point_edit_form = PostPointForm(request.POST, request.FILES,
                                             instance=post_point)
        if post_point_edit_form.is_valid():
            post_point_edit_form.save()
    return render(request, 'blog/account/post_point_edit.html',
                  {'form': post_point_edit_form,
                   'post_point': post_point,
                   'post': post})



@login_required
def post_point_add(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostPointForm()

    if request.method == 'POST':
        form = PostPointForm(request.POST,
                             request.FILES)
        if form.is_valid():
            post_point = form.save(commit=False)
            post_point.post = post
            post_point.save()

    return render(request, 'blog/account/post_point_add.html', {'form': form,
                                                                'post': post})
@login_required
def post_point_list(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    post_points=PostPoint.objects.filter(post=post)
    return render(request, 'blog/account/post_points.html',
                  {'post':post, 'post_points':post_points})


@login_required
def post_delete(request, post_id):
    try:
        post = get_object_or_404(Post, id=post_id)
        post.delete()
        return redirect('blog:dashboard')
    except Post.DoesNotExist:
        return redirect('blog:dashboard')

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_edit_form = PostForm(instance=post)
    if request.method == 'POST':
        post_edit_form = PostForm(request.POST,instance=post)
        if post_edit_form.is_valid():
            post_edit_form.save()
    return render(request,
                  'blog/account/post_edit.html',
                  {'form': post_edit_form,
                   'post': post})
@login_required
def post_add(request):
    user=request.user
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=user
            post.save()
            for tag in form.cleaned_data['tags']:
                post.tags.add(tag)
    else:
        form=PostForm()

    return render(request, 'blog/account/post_add.html',{'form':form})

@login_required
def dashboard(request):
    user=request.user
    posts_pub=Post.objects.filter(author=user,status='published')
    posts_draft=Post.objects.filter(author=user,status='draft')
    return render(request,'blog/account/dashboard.html',{'posts_pub':posts_pub,
                                                         'posts_draft':posts_draft})

def user_login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user= authenticate(request,
                               username=cd['username'],
                               password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request,'blog/account/login.html',{'form':form})
class PostListViev(ListView):
    queryset=Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

@login_required
def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:

        posts = paginator.page(1)
    except EmptyPage:

        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})



def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object, name=cd['name'], email=cd['email'], body=cd['body'])
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids=post_object.tags.values_list('id',flat=True)
    similar_posts=Post.objects.filter(tags__in=post_tags_ids,status='published').exclude(id=post_object.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                     'post_points': post_points,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts
                                                     })

mysite/blog/templates/blog/account/dashboard.html
{% extends 'blog/base_account.html' %}
{% block title %}
    Особистий кабінет
{% endblock %}
{% block account_content %}
    {% if posts_pub %}
        <h2 class="text-center mb-4">Мої опубліковані рецепти:</h2>
        <div class="card-deck">
            <div class="row row-cols-3 row-cols-md-3">
                {% for post in posts_pub %}
                    <div class="col mb-4">
                        <div class="card" style="height: 100%">
                            <a href="{{ post.get_absolut_url }}">
                                <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <a href="{{ post.get_absolut_url }}">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                </a>
                                <p class="card-text">{{ post.short_description|truncatewords:25 }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Опубліковано {{ post.publish }}.
                                    Автор {{ post.author }}</small>

                                <p> Теги:
                                    {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}
                                            ,
                                        {% endif %}
                                    {% endfor %}
                                </p>

                                <a class="btn btn-primary m-2"
                                   href="{% url 'blog:post_point_list' post.id %}">
                                    Етапи
                                </a>
                                <a class="btn btn-primary m-2"
                                   href="{% url 'blog:post_edit' post.id %}">Редагувати</a>
                                <a class="btn btn-danger m-2" href="{% url 'blog:post_delete' post.id %}">Видалити</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% endif %}
    {% if posts_draft %}
        <h2 class="text-center mb-4">Рецепти, що проходять модерацію</h2>
        <div class="card-deck">
            <div class="row row-cols-3 row-cols-md-3">
                {% for post in posts_draft %}
                    <div class="col mb-4">
                        <div class="card" style="height: 100%">
                            <a href="{{ post.get_absolut_url }}">
                                <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <a href="{{ post.get_absolut_url }}">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                </a>
                                <p class="card-text">{{ post.short_description|truncatewords:25 }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Опубліковано {{ post.publish }}.
                                    Автор {{ post.author }}</small>
                                <p> Теги:
                                    {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}
                                            ,
                                        {% endif %}
                                    {% endfor %}
                                </p>

                                <a class="btn btn-primary m-2" href="{% url 'blog:post_point_list' post.id %}">
                                    Етапи
                                </a>
                                <a class="btn btn-primary m-2"
                                   href="{% url 'blog:post_edit' post.id %}">Редагувати</a>
                                <a class="btn btn-danger m-2" href="{% url 'blog:post_delete' post.id %}">Видалити</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/account/post_add.html
{% extends "blog/base.html" %}
{% block title %}Особистий кабінет{% endblock %}
{% block content %}
    <form action="." method="post" enctype="multipart/form-data">
{{ form }}
    <button type="submit">Додати</button>
    {% csrf_token %}
    </form>
{% endblock %}

mysite/blog/templates/blog/account/post_edit.html
{% extends 'blog/base_account.html' %}
{% load  bootstrap %}
{% block title %}
    Редагувати пост
{% endblock %}
{% block account_content %}
    <div class="container text-center sign-in">
        {% if form.errors %}
            <p>{{ form.errors }}</p>
            <p>Щось забув</p>
            <form action="." class="form-sign-in login-form" method="post" enctype="multipart/form-data">
                {{ form.title|bootstrap }}
                {{ form.short_description|bootstrap }}
                {{ form.tags|bootstrap }}
                {{ form.image|bootstrap }}
                {% csrf_token %}
                <button class="btn btn-lg btn-primary mt-2" type="submit">
                    Зберегти зміни
                </button>
            </form>
        {% elif form.is_valid %}
            <h1 class="h3 mb-3 font-weight-normal">
                Пост успішно змінено
            </h1>
            <h2 class="mb-3 font-weight-normal">
                Ви можете:
            </h2>
            <a href="{% url 'blog:dashboard' %}" class="btn btn-dark">Повернутися до списку постів</a>
            <a href="{% url 'blog:post_edit' post.id %} " class="btn btn-primary">Редагувати пост</a>
        {% else %}
            <h1 class="h3 mb-3 font-weight-normal">
                Заповніть поля
            </h1>
            <form action="." class="form-sign-in login-form" method="post" enctype="multipart/form-data">
                {{ form.title|bootstrap }}
                {{ form.short_description|bootstrap }}
                {{ form.tags|bootstrap }}
                {{ form.image|bootstrap }}
                {% csrf_token %}
                <button class="btn btn-lg btn-primary mt-2" type="submit">
                    Зберегти зміни
                </button>
            </form>
        {% endif %}
    </div>
{% endblock %}

mysite/blog/templates/blog/account/post_point_add.html
{% extends 'blog/base_account.html' %}
{% load  bootstrap %}
{% block title %}
    Додати пункт поста
{% endblock %}
{% block account_content %}
    <div class="container text-center sign-in">
        {% if form.errors %}
            <p>{{ form.errors }}</p>
            <p>Щось забули</p>
            <form action="." class="form-sign-in login-form" method="post" enctype="multipart/form-data">
                {{ form.post_header|bootstrap }}
                {{ form.post_point_text|bootstrap }}
                {{ form.post_images|bootstrap }}
                {% csrf_token %}
                <button class="btn btn-lg btn-primary mt-2" type="submit">
                    Додати пункт поста
                </button>
            </form>
        {% elif form.is_valid %}
            <h1 class="h3 mb-3 font-weight-normal">
               Пункт поста добавлен
            </h1>
            <h2 class="mb-3 font-weight-normal">
                Ви можете:
            </h2>
            <a href="{% url 'blog:post_point_list' post.id %}" class="btn btn-dark">Повернутися до списку пунктів</a>
            <a href="{% url 'blog:post_point_add' post.id %}" class="btn btn-primary">Додати новий пункт поста</a>
        {% else %}
            <h1 class="h3 mb-3 font-weight-normal">
                Заповніть поля
            </h1>
            <form action="." class="form-sign-in login-form"
              method="post" enctype="multipart/form-data">
            {{ form.post_header|bootstrap }}
            {{ form.post_point_text|bootstrap }}
            {{ form.post_images|bootstrap }}

            {% csrf_token %}
            <button class="btn btn-lg btn-primary mt-2" type="submit">
                Додати пункт поста
            </button>
        </form>
        {% endif %}

    </div>
{% endblock %}

mysite/blog/templates/blog/account/post_point_edit.html
{% extends 'blog/base_account.html' %}
{% load  bootstrap %}
{% block title %}
    Редагувати Пункт поста
{% endblock %}
{% block account_content %}
    <div class="container text-center sign-in">
        {% if form.errors %}
            <p>{{ form.errors }}</p>
            <p>Щось забув</p>
            <form action="." class="form-sign-in login-form" method="post" enctype="multipart/form-data">
                {{ form.post_header|bootstrap }}
                {{ form.post_point_text|bootstrap }}
                {{ form.post_images|bootstrap }}
                {% csrf_token %}
                <button class="btn btn-lg btn-primary mt-2" type="submit">
                    Зберегти зміни
                </button>
            </form>
        {% elif form.is_valid %}
            <h1 class="h3 mb-3 font-weight-normal">
                Пункт поста успішно змінено
            </h1>
            <h2 class="mb-3 font-weight-normal">
                Ви можете:
            </h2>
            <a href="{% url 'blog:post_point_list' post.id %}" class="btn btn-dark">Повернутися до списку пунктів</a>
            <a href="{% url 'blog:post_point_edit' post_point.id %}" class="btn btn-primary">Знову змінити цей
                пункт</a>
        {% else %}
            <h1 class="h3 mb-3 font-weight-normal">
                Запувніть поля
            </h1>
            <form action="." class="form-sign-in login-form"
                  method="post" enctype="multipart/form-data">
                {{ form.post_header|bootstrap }}
                {{ form.post_point_text|bootstrap }}
                {{ form.post_images|bootstrap }}

                {% csrf_token %}
                <button class="btn btn-lg btn-primary mt-2" type="submit">
                   Зберегти зміни
                </button>
            </form>
        {% endif %}

    </div>
{% endblock %}

mysite/blog/templates/blog/account/post_points.html
{% extends 'blog/base_account.html' %}
{% block title %}
    Особистий кабінет
{% endblock %}
{% block account_content %}
    <div class="title-post-point-page">
        <h2 class="text-center mb-4">
           Етапи приготування "{{ post.title }}"
        </h2>
        <a class="btn btn-primary m-2 add-point" href="{% url 'blog:post_point_add' post.id %}">
            Додати етап
        </a>
    </div>

    <div class="card-deck">
        <div class="row row-cols-3 row-cols-md-3">
            {% for p_p in post_points %}
                <div class="col mb-4" >
                    <div class="card" style="height: 100%">
                        {% if p_p.post_point_image %}
                            <a href="{{ post.get_absolute_url }}">
                                <img src="{{ MEDIA_URL }}{{ p_p.post_point_image.url }}"
                                     class="card-img-top" alt="...">
                            </a>
                        {% else %}
                             <a href="{{ post.get_absolute_url }}">
                                <img src="https://thumbs.dreamstime.com/z/no-image-available-icon-photo-camera-flat-vector-illustration-132483296.jpg"
                                     class="card-img-top" alt="...">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <a href="#">
                                <h5 class="card-title">
                                    {{ p_p.post_point_header }}
                                </h5>
                            </a>
                            <p class="card-text">
                                {{ p_p.post_point_text|truncatewords:25 }}
                            </p>
                        </div>
                        <div class="card-footer">

                            <a class="btn btn-primary m-2" href="{% url 'blog:post_point_edit' p_p.id %}">Редагувати</a>
                            <a class="btn btn-danger m-2" href="{% url 'blog:post_point_delete' p_p.id %}">Видалити</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/account/profile.html
{% extends 'blog/base_account.html' %}
{% load  bootstrap %}
{% block title %}
    Редагувати профіль
{% endblock %}
{% block account_content %}
    <div class="container text-center sign-in">
        {% if user_form.errors %}
            <p>{{ user_form.errors }}</p>
                <p>Щось забув</p>
        {% elif user_form.is_valid  %}
            <h1 class="h3 mb-3 font-weight-normal">
                Дані профіля змінено
            </h1>
            <a href="{% url 'blog:dashboard' %}" class="btn btn-dark mb-4">Повернутися до списку постів</a>
        {% else %}
            <h1 class="h3 mb-3 font-weight-normal">
                Заповніть поля
            </h1>
        {% endif %}
        <form action="." class="form-sign-in login-form" method="post" enctype="multipart/form-data">
            {{ user_form.first_name|bootstrap }}
            {{ user_form.last_name|bootstrap }}
            {{ user_form.username|bootstrap }}
            {{ user_form.email|bootstrap }}

            {% csrf_token %}
            <button class="btn btn-lg btn-primary mt-2" type="submit">
                Зберегти зміни
            </button>
        </form>
    </div>
{% endblock %}